# Reusable Workflow, to be called from SDK repositories, to prevent repetition for this common pattern.
# see: https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: SDK Features

on:
  workflow_call:
    inputs:
      repository-name:
        required: true
        type: string
    secrets:
      ABLY_AWS_ACCOUNT_ID_SDK:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: ably/features-action@v1
        id: features

      - name: Configure AWS Credentials
        # at some point AWS will release a `v2` of this action. See:
        # https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/ably-sdk-builds-${{ inputs.repository-name }}
          role-session-name: "${{ github.run_id }}-${{ github.run_number }}"

      - uses: ably/sdk-upload-action@v2
        with:
          sourcePath: ${{ steps.features.outputs.matrix-path }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: ${{ steps.features.outputs.matrix-artifact-name }}
